requires = [
    "tox==4.44.0",
    "tox-uv==1.29.0"
]
env_list = ["py313", "coverage"]

[env_run_base]
package = "editable"
runner = "uv-venv-lock-runner"
dependency_groups = ["dev"]
commands = [
    ["pytest", "--cov=src", "--cov-report=term-missing", "{posargs}"]
]

[env_run_base.setenv]
PYTHONPATH = "src"


[env.py313]
basepython = ["python3.13"]

[env.coverage]
skip_install = true
dependency_groups = ["dev"]
commands = [
    ["coverage", "report"],
    ["coverage", "xml"],
    ["coverage", "html"]
]
