
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 720
BOTTOM_MENU_HEIGHT = 120

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
CYAN = (0, 255, 255)
GRAY = (128, 128, 128)

# Game settings
FPS: int = 60
RESOURCE_SIZE: int = 15
RESOURCE_RADIUS: float = 5.0
HARVEST_SEARCH_RADIUS: float = 300.0

BUILDING_SIZE: int = 40
BUILDING_RADIUS: float = 10.0

UNIT_SPEED: float = 2.0
UNIT_SIZE: int = 30
UNIT_RADIUS: float = 10.0
UNIT_MAX_CARRY: int = 10
UNIT_LIFE: int = 5
UNIT_ATTACK_DAMAGE: int = 3
UNIT_ATTACK_RANGE: int = 0
UNIT_ATTACK_SPEED: int = 1
UNIT_ATTACK_IDLE: int = 10
UNIT_ATTACK_MODIFIER: int = 0
UNIT_SHIELD_MODIFIER: int = 0
UNIT_ATTACK_TYPE: str = "Melee"

KNIGHT_SPEED: float = 2.5
KNIGHT_SIZE: int = 40
KNIGHT_RADIUS: float = 13.0
KNIGHT_MAX_CARRY: int = 3
KNIGHT_LIFE: int = 100
KNIGHT_ATTACK_DAMAGE: int = 10
KNIGHT_ATTACK_RANGE: int = 50
KNIGHT_ATTACK_SPEED: int = 1
KNIGHT_ATTACK_IDLE: int = 10
KNIGHT_ATTACK_MODIFIER: int = 0
KNIGHT_SHIELD_MODIFIER: int = 0
KNIGHT_ATTACK_TYPE: str = "Melee"

ARCHER_SPEED: float = 2.0
ARCHER_SIZE: int = 40
ARCHER_RADIUS: float = 13.0
ARCHER_MAX_CARRY: int = 2
ARCHER_LIFE: int = 70
ARCHER_ATTACK_DAMAGE: int = 5
ARCHER_ATTACK_RANGE: int = 50
ARCHER_ATTACK_SPEED: int = 1
ARCHER_ATTACK_IDLE: int = 10
ARCHER_ATTACK_MODIFIER: int = 0
ARCHER_SHIELD_MODIFIER: int = 0
ARCHER_ATTACK_TYPE: str = "Ranged"

MAGE_SPEED: float = 1.5
MAGE_SIZE: int = 40
MAGE_RADIUS: float = 13.0
MAGE_MAX_CARRY: int = 1
MAGE_LIFE: int = 30
MAGE_ATTACK_DAMAGE: int = 5
MAGE_ATTACK_RANGE: int = 50
MAGE_ATTACK_SPEED: int = 1
MAGE_ATTACK_IDLE: int = 10
MAGE_ATTACK_MODIFIER: int = 0
MAGE_SHIELD_MODIFIER: int = 0
MAGE_ATTACK_TYPE: str = "Ranged"